/* ========================================================================
 * SAMPLE ESSAYS — one fully completed example per academic level.
 *
 * Each sample shows what a top-mark essay looks like at that level. Users
 * can walk through it to see how every step of the app maps to real prose.
 *
 * Structure of each sample:
 *   level, title, essayType, wordCount, citationStyle,
 *   brief, decoded {commandWords, audience, scope, constraints, success},
 *   rubricMet, researchQuestion, thesis, sections[{name, body}].
 *
 * NB: these samples are illustrative. They are written in the curriculum's
 * voice (curriculum's terms: PEEL, RADAR, "So what?", They Say / I Say).
 * ====================================================================== */

const SAMPLE_ESSAYS = {

  /* ============= FOUNDATION / PRE-UNIVERSITY ============= */
  foundation: {
    level: "foundation",
    title: "Should social media platforms be regulated to protect adolescent mental health?",
    essayType: "argumentative",
    wordCount: 1200,
    citationStyle: "APA 7th",
    brief: "Write a 1,200-word argumentative essay responding to the following question: 'Should social media platforms be regulated to protect adolescent mental health?' Use at least three credible sources, follow APA 7 citation style, and address at least one counterargument.",
    decoded: {
      commandWords: "should — argue a debatable position",
      audience: "Module tutor + external moderator; informed non-specialists",
      scope: "Adolescents 13–18, social media platforms with feeds (Instagram, TikTok, Snapchat), 2018–2024",
      constraints: "1,200 words ±10%; ≥3 peer-reviewed sources; APA 7; counterargument required",
      success: "Clear arguable thesis; PEEL paragraphs; RADAR-passed sources; one fully-developed counterargument refuted with evidence."
    },
    researchQuestion: "Should governments regulate algorithmic feeds on social media platforms used by adolescents in order to reduce documented harms to mental health?",
    thesis: "Although social media platforms create real opportunities for adolescent connection and learning, governments should regulate their algorithmic feeds because the platforms' own internal research, longitudinal psychiatric studies, and a converging body of evidence on attention and sleep all show that current designs cause measurable harm.",
    sections: [
      { name: "Introduction", body: "In 2021, internal Facebook research leaked to the press confirmed what many parents and clinicians already suspected: the platform's own teams found that Instagram made body-image issues worse for one in three teenage girls (Wells et al., 2021). Adolescents now spend an average of 4.8 hours per day on social platforms (Rideout et al., 2022), at a developmental stage when sleep, peer comparison, and identity formation are most fragile. This essay argues that, although social media platforms create real opportunities for adolescent connection and learning, governments should regulate their algorithmic feeds because the platforms' own internal research, longitudinal psychiatric studies, and a converging body of evidence on attention and sleep all show that current designs cause measurable harm." },
      { name: "Body 1 — Internal evidence from the platforms", body: "The most damning evidence for harm comes from the platforms themselves. According to the 2021 Facebook Files, Meta's internal researchers concluded that 'we make body image issues worse for one in three teen girls' (Wells et al., 2021, p. 1). The same investigation surfaced data showing that 13.5 per cent of teenage girls with suicidal thoughts traced them to Instagram. This shows that the harms are not hypothetical: they are documented in the firms' own metrics by their own employees. Because the evidence comes from inside, it cannot easily be dismissed as moral panic, and it directly contradicts the platforms' public-facing safety messaging — which is precisely the kind of asymmetry regulation is designed to correct." },
      { name: "Body 2 — Independent psychiatric and longitudinal research", body: "Independent research reaches the same conclusion. Twenge and colleagues' (2018) analysis of nationally-representative US datasets showed that the rise of smartphone-mediated social media after 2012 tracked almost perfectly with rising rates of adolescent depression, self-harm, and suicide — patterns absent in earlier generations. A 2023 systematic review of 38 longitudinal studies (Orben et al., 2023) found a small-to-moderate but consistent association between heavy social-media use and depressive symptoms, with effect sizes largest among 11- to 13-year-old girls. This evidence is significant because it controls for reverse causation: heavy use predicts later depression, not the other way around. This is the kind of independent confirmation that, combined with the platforms' own data, makes a regulatory response defensible." },
      { name: "Body 3 — Mechanisms: attention and sleep", body: "The mechanism is now understood well enough to design targeted regulation. Algorithmic feeds are tuned to maximise time-on-platform, which they achieve by exploiting variable-ratio reward schedules — the same mechanism that makes slot machines compelling (Alter, 2017). For adolescents, two well-documented consequences follow. First, attention fragments: a meta-analysis of 27 studies found average sustained-attention spans dropping by roughly 30 per cent over a decade of heavy short-form video use (Lukianoff & Schmidt, 2024). Second, sleep is disrupted: 70 per cent of adolescents in a recent UK cohort study used their phones after their official bedtime, and those who did averaged 47 minutes less sleep (Royal College of Paediatrics, 2023). These mechanisms link the harms in Bodies 1 and 2 to specific design choices that a regulator can require platforms to change — for example, by mandating non-personalised feeds by default for under-18 accounts." },
      { name: "Counterargument — They say / I say", body: "Critics of regulation argue that the burden should fall on parents and educators, not on the state, and that regulating algorithmic curation amounts to a curtailment of free expression and innovation. However, this view overlooks two things. First, parents cannot competently negotiate against products specifically engineered to override the self-regulatory capacities of the developing brain (Twenge et al., 2018); asking individual families to police platforms is asking them to win an asymmetric contest. Second, the proposal here is not to ban content but to constrain design — specifically, to require non-personalised feeds by default for minors and to prohibit dark-pattern engagement loops. Comparable design regulations already operate for children's toys (small-parts rules), gambling (age gates), and tobacco advertising; the principle is well established." },
      { name: "Conclusion", body: "Internal industry research, independent longitudinal studies, and a clear mechanistic story all point in the same direction: the current design of algorithmic feeds is causing measurable harm to adolescent mental health, and individual responsibility alone is structurally unable to fix it. Targeted regulation — defaulting under-18 accounts to non-personalised feeds and banning specific engagement loops — does not require banning social media or limiting expression; it requires designing for the developmental stage of the user, which every other consumer-facing industry already does. The cost of inaction is being absorbed, daily, by the young people the platforms most aggressively pursue." }
    ],
    references: [
      "Alter, A. (2017). Irresistible: The rise of addictive technology and the business of keeping us hooked. Penguin Press.",
      "Lukianoff, G., & Schmidt, J. (2024). Sustained attention and short-form video: A meta-analysis. Journal of Adolescent Research, 39(2), 145–168.",
      "Orben, A., Przybylski, A. K., Blakemore, S.-J., & Kievit, R. A. (2023). Windows of developmental sensitivity to social media. Nature Communications, 14, 1649.",
      "Rideout, V., Peebles, A., Mann, S., & Robb, M. B. (2022). Common Sense Census: Media use by tweens and teens. Common Sense Media.",
      "Royal College of Paediatrics and Child Health. (2023). State of child health: Digital lives report.",
      "Twenge, J. M., Joiner, T. E., Rogers, M. L., & Martin, G. N. (2018). Increases in depressive symptoms, suicide-related outcomes, and suicide rates among U.S. adolescents after 2010. Clinical Psychological Science, 6(1), 3–17.",
      "Wells, G., Horwitz, J., & Seetharaman, D. (2021, September 14). Facebook knows Instagram is toxic for teen girls. The Wall Street Journal."
    ],
    walkthrough: [
      { step: "Brief Breakdown", note: "Command word 'should' → argumentative. Audience: tutor + moderator. Constraint: 1,200 words, ≥3 sources, APA 7, counterargument required." },
      { step: "Research Question", note: "Specific: regulates algorithmic feeds, not all social media. Researchable: large body of evidence exists. Arguable: clear opposing view." },
      { step: "Essay Type", note: "Argumentative — the question asks 'should', which demands a debatable position." },
      { step: "Thesis", note: "Topic (social media + adolescents) + Position (should regulate) + Rationale (3 reasons that become Body 1–3)." },
      { step: "PEEL bodies", note: "Each body opens with the Point, gives Evidence with citation, Explains 'this shows that…', and Links forward." },
      { step: "Counter", note: "Strongest opposing view (parents' responsibility + free expression) fairly stated, then refuted with two specific rebuttals." }
    ]
  },

  /* ============= UNDERGRADUATE ============= */
  undergraduate: {
    level: "undergraduate",
    title: "From feed to filter: how algorithmic curation reshapes political opinion formation among UK 18–25-year-olds",
    essayType: "analytical",
    wordCount: 3000,
    citationStyle: "Harvard",
    brief: "Write a 3,000-word research essay analysing one mechanism by which a digital platform shapes a democratic outcome. Include a focused literature review (~700 words), a coherent argument with original interpretation, ≥8 peer-reviewed sources, and a discussion of methodological limitations. Harvard referencing.",
    decoded: {
      commandWords: "analyse — break down a mechanism and reveal what it means",
      audience: "Module tutor + 2nd marker; senior politics students",
      scope: "UK; 18–25 cohort; 2016–2024; political-opinion formation specifically (not voting behaviour)",
      constraints: "3,000 words; ≥8 peer-reviewed; Harvard; literature review section required; limitations discussed",
      success: "Original analytical thesis; thematic literature review (not summary); evidence-driven argument; clear methodological self-awareness."
    },
    researchQuestion: "How do algorithmically curated feeds reshape the process by which UK 18–25-year-olds form political opinions, and what does this mean for democratic deliberation?",
    thesis: "Algorithmic curation does not merely accelerate exposure to political content among UK 18–25-year-olds; it restructures the cognitive and social conditions under which political opinions are formed — collapsing the deliberative window, narrowing exposure to disconfirming evidence, and substituting affective identification for argumentative reasoning. The result is opinion formation that is faster, more confident, and less revisable, with significant implications for democratic deliberation.",
    sections: [
      { name: "Abstract", body: "This essay analyses one mechanism — algorithmic curation — by which digital platforms reshape political opinion formation among 18–25-year-old UK voters. Drawing on 18 peer-reviewed studies from political communication, media psychology, and HCI, it argues that algorithmic curation collapses the deliberative window between exposure and opinion formation, narrows exposure to disconfirming evidence, and substitutes affective identification for argumentative reasoning. The implications for democratic deliberation are significant: faster, more confident, less revisable political opinions are precisely the conditions under which deliberative correction is hardest. The essay closes by noting that the strongest evidence is correlational and by suggesting two preregistered experimental designs that would resolve the remaining causal uncertainty." },
      { name: "1. Introduction", body: "Britain's 18–25-year-olds form their political opinions, increasingly, in a context that no previous generation has encountered: a feed whose contents are not curated by editors, peers, or chance, but by a machine-learning system optimised for engagement (Stark and Stegmann, 2020). Existing research has documented striking shifts in this cohort's information diet (Ofcom, 2023), but most of the public conversation treats algorithmic curation as a faster pipe — more content, more quickly. This framing misses what is structurally different. This essay argues that algorithmic curation does not merely accelerate exposure to political content; it restructures the cognitive and social conditions under which political opinions are formed. Section 2 reviews the literature in three thematic strands. Section 3 develops the argument across three claims, each grounded in PEEL-structured evidence. Section 4 addresses the strongest counterargument — that selective exposure is not new — and refutes it. Section 5 concludes with the implications for democratic deliberation and methodological limitations." },
      { name: "2. Literature Review", body: "Three thematic strands organise the literature.\n\nFirst, on **exposure and information diet**, Ofcom (2023) and Newman et al. (2024) show that 73 per cent of UK 18–24-year-olds now name social platforms as their main news source, with TikTok overtaking the BBC for under-25s in 2024. Bakshy et al. (2015) and Cinelli et al. (2021) demonstrate that algorithmic recommendation produces measurably narrower content exposure than chronologically-ordered feeds, even when controlling for user self-selection — though the effect size is contested (Allcott et al., 2020).\n\nSecond, on **affective polarisation**, Iyengar et al. (2019), Settle (2018), and Bail (2021) converge on the finding that exposure via algorithmic feeds is associated with stronger affective dislike of out-groups, but Bail et al.'s (2018) field experiment shows that simply exposing users to the *other side* — without changing the affective infrastructure of the platform — can actually deepen polarisation, suggesting that the curated *form* matters more than the content alone.\n\nThird, on **opinion formation as a cognitive process**, the Elaboration Likelihood Model (Petty and Cacioppo, 1986) predicts that fast, low-effort exposure favours peripheral-route processing (affect, cues, identity) over central-route processing (argument, evidence, deliberation). Recent work by Pennycook and Rand (2022) extends this to social-media contexts, finding that even people capable of analytical reasoning default to intuitive processing when scrolling.\n\nTogether, these strands establish *that* algorithmic curation changes exposure and *that* exposure is associated with affective polarisation, but they leave a gap: the mechanism by which curation reshapes opinion formation itself — not just its outputs — is under-theorised in the UK 18–25 context. This essay addresses that gap." },
      { name: "3.1 First claim — The deliberative window collapses", body: "**Point.** Algorithmic curation collapses the temporal gap between exposure and opinion, the gap in which deliberation historically happens. **Evidence.** Average dwell-time per political post in the TikTok For You feed is 4.3 seconds (Zhao and Wu, 2023); the median time between first exposure and a like/share on Twitter/X is 11 seconds (Vosoughi et al., 2018). Compare this to the Reuters Institute's (2024) finding that British newspaper readers spent a median of 4–6 minutes per political article in the 2010s. **Explanation.** This shows that opinion formation now occurs inside the window in which central-route processing is *neurally impossible*: working-memory consolidation requires several seconds (Cowan, 2017). The opinion that emerges is therefore necessarily a peripheral-route opinion — based on cues, affect, and identification rather than argument. **Link.** This mechanism is necessary but not sufficient; the *content* of the cues encountered also shapes the resulting opinion, which is the focus of the second claim." },
      { name: "3.2 Second claim — Disconfirming evidence is structurally rare", body: "**Point.** Algorithmic feeds expose UK 18–25-year-olds to a narrower band of disconfirming political content than any prior media environment. **Evidence.** Cinelli et al. (2021) measured echo-chamber strength across five platforms; algorithmically curated feeds (Facebook, YouTube) produced exposure that was 2.3× more ideologically homogeneous than chronological feeds (Reddit, raw timelines). Within the UK cohort specifically, an internal Ofcom (2023) experiment found that fresh TikTok accounts created in left-leaning postcodes received politically asymmetric content within 14 video impressions. **Explanation.** Karl Popper's (1963) criterion for rational opinion change is exposure to potentially-falsifying evidence; in algorithmically curated feeds, that exposure is structurally rare and, when it does occur, is typically framed adversarially. This is not the same as choosing a partisan newspaper — Popper's criterion was satisfied by the existence of competing newspapers in a shared public sphere — because there is no shared public sphere on a personalised feed. **Link.** The combination of a collapsed deliberative window (Claim 1) and structural rarity of disconfirming content (Claim 2) sets the stage for the third and final structural change: the substitution of affect for argument." },
      { name: "3.3 Third claim — Affective identification replaces argument", body: "**Point.** Under these conditions, affective identification with in-group signals substitutes for argumentative reasoning as the route to political opinion. **Evidence.** Bail's (2021) work shows that political opinions held by US and UK social-media-heavy users are 40 per cent more affectively charged than opinions held by news-heavy users, even controlling for ideology and demographics. Pennycook and Rand (2022) replicated this in a UK sample of 18–25-year-olds: even cognitively able participants defaulted to identity-based processing on platform content. **Explanation.** This is significant because affective opinions are harder to revise. The Reuters Institute (2024) found that UK 18–25-year-olds who reported their main news source as a social platform were three times less likely to update their political view in response to high-quality counter-evidence than those whose main source was the BBC or a national newspaper. Affective opinions feel like identity; identity is sticky. **Link.** Taken together, the three mechanisms — collapsed window, narrowed exposure, affective substitution — describe a structural reshaping of the *process* of political opinion formation, not merely its content." },
      { name: "3.4 Counterargument & refutation — They say / I say", body: "**They say.** Selective exposure is not new; people have always read newspapers and watched television channels that confirmed their views (Sunstein, 2001). The deliberative ideal these critics describe was never empirically realised, so the claim that algorithms broke it is, on this view, romantic.\n\n**I say.** This critique would be decisive if the *only* mechanism at work were selective exposure. But the analysis above identifies two further mechanisms not present in the newspaper era: the collapse of the deliberative window (Claim 1) and the substitution of affective for argumentative processing at the *moment of exposure* itself (Claim 3). Both are properties of feed architecture, not of selectivity. Sunstein's (2001) critique remains correct about exposure but underestimates what changes when exposure is interleaved at sub-second cadence with affect-laden cues. The deliberative ideal may never have been fully realised, but it was structurally possible in the newspaper era and is structurally precluded by the feed." },
      { name: "4. Methodological limitations", body: "Two limitations of the present essay should be noted. First, the strongest evidence on attribution remains correlational; the most compelling causal study (Bail et al., 2018) inverted expectations rather than confirming them, suggesting the causal story is more complex than the cleanest version of this argument would imply. A preregistered between-subjects field experiment that randomised UK 18–25-year-olds to algorithmically curated versus chronologically ordered feeds for six months would substantially resolve this. Second, the analysis here treats 'algorithmic curation' as homogeneous; in practice, recommender systems vary in substantial ways between platforms (Stark and Stegmann, 2020). A platform-specific replication would strengthen the argument." },
      { name: "5. Conclusion", body: "Algorithmic curation reshapes political opinion formation among UK 18–25-year-olds not by speeding up an existing process but by restructuring it — collapsing the deliberative window, narrowing disconfirming exposure, and substituting affective identification for argumentative reasoning. The democratic implication is uncomfortable: faster, more confident, less revisable political opinions are exactly the conditions under which deliberative correction is most difficult. The remedies that follow from this analysis are therefore not media-literacy campaigns — these address the content of opinions, not their architecture — but design-level interventions: chronological feed defaults, friction at the share-button, and exposure-rotation in recommender systems. None of these can or should mandate the deliberative ideal; what they can do is restore the *structural possibility* of it." }
    ],
    references: [
      "Allcott, H., Braghieri, L., Eichmeyer, S. and Gentzkow, M., 2020. The welfare effects of social media. American Economic Review, 110(3), pp.629–676.",
      "Bail, C.A., 2021. Breaking the social media prism. Princeton University Press.",
      "Bail, C.A., et al., 2018. Exposure to opposing views on social media can increase political polarization. PNAS, 115(37).",
      "Bakshy, E., Messing, S. and Adamic, L.A., 2015. Exposure to ideologically diverse news and opinion on Facebook. Science, 348(6239), pp.1130–1132.",
      "Cinelli, M., et al., 2021. The echo chamber effect on social media. PNAS, 118(9).",
      "Cowan, N., 2017. The many faces of working memory and short-term storage. Psychonomic Bulletin & Review, 24, pp.1158–1170.",
      "Iyengar, S., et al., 2019. The origins and consequences of affective polarization in the United States. Annual Review of Political Science, 22.",
      "Newman, N., et al., 2024. Reuters Institute Digital News Report 2024. Reuters Institute for the Study of Journalism.",
      "Ofcom, 2023. News consumption in the UK: 2023.",
      "Pennycook, G. and Rand, D., 2022. Accuracy prompts are a replicable and generalizable approach for reducing the spread of misinformation. Nature Communications, 13.",
      "Petty, R.E. and Cacioppo, J.T., 1986. The Elaboration Likelihood Model of persuasion. In Advances in Experimental Social Psychology.",
      "Popper, K., 1963. Conjectures and refutations. Routledge.",
      "Reuters Institute, 2024. Digital News Report — UK supplementary.",
      "Settle, J.E., 2018. Frenemies: How social media polarizes America. Cambridge University Press.",
      "Stark, B. and Stegmann, D., 2020. Are algorithms a threat to democracy? AlgorithmWatch.",
      "Sunstein, C., 2001. Republic.com. Princeton University Press.",
      "Vosoughi, S., Roy, D. and Aral, S., 2018. The spread of true and false news online. Science, 359(6380), pp.1146–1151.",
      "Zhao, S. and Wu, M., 2023. Dwell-time dynamics on short-form video platforms. New Media & Society, 25(8)."
    ],
    walkthrough: [
      { step: "Brief Breakdown", note: "'Analyse' command word → Analytical essay. Strict word count, peer-reviewed source requirement, mandatory literature-review section." },
      { step: "Research Question", note: "Specific (one platform feature: algorithmic curation), Researchable (mature literature exists), Significant (democratic-deliberation stakes), Arguable, narrow Scope (UK 18–25)." },
      { step: "Literature Review", note: "Three thematic strands organised by what the literature does and does not establish — ending with the explicit gap the essay fills." },
      { step: "Argument structure", note: "Three analytical claims, each a PEEL paragraph. The Links explicitly compose into a single mechanism." },
      { step: "Counter", note: "Sunstein's selective-exposure critique addressed head-on and refuted by isolating which mechanisms are genuinely new." },
      { step: "Limitations", note: "The honest appraisal at the UG level — admits the strongest causal evidence is still missing and proposes a concrete experiment." }
    ]
  },

  /* ============= POSTGRADUATE / MASTERS ============= */
  postgraduate: {
    level: "postgraduate",
    title: "Affective architectures of attention: a mixed-methods investigation of algorithmic curation and political opinion formation among UK 18–25-year-olds",
    essayType: "research-proposal",
    wordCount: 15000,
    citationStyle: "APA 7th",
    brief: "Submit a 15,000-word Masters dissertation on a topic relevant to digital society. Must follow the institution's standard thesis format (frontmatter, 5 chapters, appendices, references). Include original empirical work (qualitative, quantitative, or mixed methods). Address ethical considerations.",
    decoded: {
      commandWords: "investigate — empirical research with explicit aims and objectives",
      audience: "Supervisor + 2 examiners; specialists in digital society & political communication",
      scope: "UK 18–25 cohort; 2024 fieldwork; algorithmic feeds on Instagram + TikTok",
      constraints: "15,000 words; APA 7; ethical approval required; mixed methods preferred; standard 5-chapter format",
      success: "Original empirical contribution; theoretical framework explicit; methodology defensible; findings linked back to RQs; thoughtful limitations."
    },
    researchQuestion: "RQ1: How do UK 18–25-year-olds describe the experience of forming political opinions via algorithmically curated feeds? RQ2: To what extent does feed architecture (chronological vs. algorithmic) predict measurable shifts in opinion confidence and revisability? RQ3: What design or policy interventions would participants consider acceptable?",
    thesis: "This dissertation argues, on the basis of 24 semi-structured interviews and a 6-week within-subject experimental manipulation of feed architecture, that algorithmic curation reshapes political opinion formation among UK 18–25-year-olds through three distinct mechanisms (temporal compression, affective substitution, identity binding) and that design-level interventions are both empirically supported and acceptable to the cohort itself.",
    sections: [
      { name: "v. Abstract (extract)", body: "This mixed-methods dissertation investigates how algorithmic curation reshapes political opinion formation among UK 18–25-year-olds. Drawing on 24 semi-structured interviews and a 6-week within-subject experiment manipulating feed architecture (n = 96), the study advances three findings. First, participants describe political opinion formation as a felt rather than reasoned process — a finding that maps closely onto the Elaboration Likelihood Model's peripheral route. Second, randomly assigned exposure to a chronological feed measurably increased opinion-revisability (Cohen's d = 0.41) and reduced confidence in unsupported claims (d = 0.36) within six weeks. Third, participants overwhelmingly supported design-level interventions (78 per cent) when given concrete examples, but were sceptical of content-moderation interventions (32 per cent). The dissertation contributes a three-mechanism model of curated opinion formation, an experimentally validated design intervention, and a participant-derived acceptability matrix for digital-platform regulation." },
      { name: "Chapter 1: Introduction (extract — §1.2 Research Problem)", body: "Existing research on algorithmic curation and politics is dominated by two paradigms: large-scale observational studies of exposure (Bakshy et al., 2015; Cinelli et al., 2021) and field experiments testing content interventions (Bail et al., 2018; Pennycook & Rand, 2022). Both are valuable, but both leave a gap. The first describes *what* people see without explaining *how* they form opinions about it. The second tests interventions on content but rarely on *architecture*. This dissertation addresses the gap by asking, through both qualitative and quantitative methods, how the architecture of the feed (independently of content) reshapes the cognitive and social process of opinion formation among UK 18–25-year-olds. The research problem is therefore both descriptive (what is happening?) and interventional (what can be done about it?)." },
      { name: "Chapter 2: Literature Review (extract — §2.4 Gap in the literature)", body: "The literature establishes three things about algorithmic feeds and politics. It establishes that exposure narrows under algorithmic curation (Cinelli et al., 2021); that affective polarisation is associated with platform-heavy news diets (Iyengar et al., 2019; Bail, 2021); and that some content interventions backfire (Bail et al., 2018). It does not establish how the *architecture* of the feed reshapes the cognitive process of opinion formation independently of content, nor what design interventions UK 18–25-year-olds themselves consider acceptable. The present study addresses both gaps through mixed methods." },
      { name: "Chapter 3: Research Methodology (extract — §3.7 Ethical considerations)", body: "Ethical approval was granted by the University Research Ethics Committee (Ref 2024/SOC/0143). All participants gave informed written consent and were free to withdraw at any point up to publication. Interview transcripts were pseudonymised at the point of transcription; raw recordings were stored on encrypted institutional storage and will be destroyed at the end of the project archival period (5 years). The experimental manipulation used participants' own accounts; the chronological-feed condition was activated via documented platform settings, no third-party software was installed, and the study's debrief explained reversibility. Participants in distress could withdraw and were given signposting to NHS mental-health resources." },
      { name: "Chapter 4: Findings (extract — §4.3.1 RQ1 finding)", body: "Across 24 interviews, participants consistently described opinion formation in language that emphasised feeling over reasoning. Asked how they came to hold a recent political opinion, 19 of 24 used affective verbs ('felt', 'clicked with', 'made sense to me') rather than analytical ones ('I worked out', 'I weighed up'). This finding maps closely onto the Elaboration Likelihood Model's peripheral route (Petty & Cacioppo, 1986). Crucially, participants were able to describe this distinction themselves when prompted: 'I know I should think about it more but the feed kind of decides for you' (P14, 22, female). This metacognitive awareness is novel — prior literature has assumed participants are unaware of the affective route they take." },
      { name: "Chapter 5: Conclusions & Recommendations (extract — §5.3 Theoretical contributions)", body: "The dissertation makes three theoretical contributions. First, it operationalises the Elaboration Likelihood Model for algorithmic-feed contexts, showing that the peripheral route is the *default* rather than an exception under feed architecture. Second, it introduces a three-mechanism model — temporal compression, affective substitution, identity binding — that decomposes algorithmic curation's effect into separately addressable design properties. Third, it demonstrates that opinion-revisability can be experimentally manipulated by feed architecture alone, independently of content moderation. Together these contributions reorient the policy debate from what users see to how they encounter what they see." }
    ],
    walkthrough: [
      { step: "Frontmatter", note: "Certification, dedication, acknowledgements, abstract, ToC, lists of figures/tables, abbreviations + glossary — all formal pages before Chapter 1." },
      { step: "Aims & Objectives", note: "§1.3 cleanly separates the overall aim from 3–5 specific objectives, each phrased with an action verb." },
      { step: "Theoretical framework", note: "Explicitly named (Elaboration Likelihood Model) and operationalised in Ch.2/Ch.3." },
      { step: "Methodology", note: "Mixed methods justified, sampling explained, ethical approval cited, validity/reliability addressed." },
      { step: "Findings vs. Discussion", note: "Ch.4 presents findings neutrally; Ch.5 interprets in light of the literature." },
      { step: "Recommendations", note: "Practical (for platforms) + policy (for regulators) + future research — all derived from the findings." }
    ]
  },

  /* ============= DOCTORAL / PHD ============= */
  doctoral: {
    level: "doctoral",
    title: "Curated cognition: a multi-study investigation of feed architecture, opinion formation, and democratic capacity in early-career UK voters",
    essayType: "research-proposal",
    wordCount: 80000,
    citationStyle: "APA 7th",
    brief: "An original doctoral thesis making a substantial contribution to knowledge in digital society / political communication.",
    decoded: {
      commandWords: "investigate, theorise, and contribute — original empirical and theoretical work",
      audience: "Supervisory team + viva examiners (internal + external) + the wider scholarly community",
      scope: "UK 18–25 cohort; three linked studies over 36 months; theoretical contribution to political-communication theory",
      constraints: "80,000 words; rigorous ethical clearance; original contribution to knowledge required; viva-defensible",
      success: "Original theoretical framework; methodological rigour across three studies; clearly stated and defended contribution to knowledge; reflective on limitations."
    },
    researchQuestion: "RQ1 (qualitative): What is the phenomenology of political opinion formation under algorithmic feed conditions? RQ2 (experimental): What is the causal effect of feed architecture on opinion revisability, controlling for content? RQ3 (interventional): What design and policy interventions are acceptable, effective, and durable?",
    thesis: "This thesis develops and defends a three-mechanism architectural model of political opinion formation under algorithmic curation, demonstrating across three linked studies that feed architecture causally shapes the cognitive process of opinion formation (independently of content), that the effects are durable and asymmetric across the political spectrum, and that design-level interventions are both more acceptable and more effective than content-level interventions among UK 18–25-year-olds.",
    sections: [
      { name: "v. Abstract (extract)", body: "This thesis investigates how the architecture of algorithmically curated feeds reshapes political opinion formation among UK 18–25-year-olds. Across three linked studies — a phenomenological interview study (n = 32), a longitudinal between-subjects experiment (n = 240, 12 weeks), and a deliberative policy-co-design study (n = 6 panels × 8 participants) — the thesis develops and defends a three-mechanism architectural model (temporal compression, affective substitution, identity binding) that decomposes algorithmic curation into separately measurable and intervenable design properties. The thesis makes three original contributions to knowledge: (i) a theoretical model that reorients political-communication theory from content to architecture; (ii) the first causally identified estimate of feed-architecture effects on opinion revisability; and (iii) a participant-co-designed regulatory framework that has since been formally tabled by a UK Parliamentary committee." },
      { name: "Chapter 1: Introduction (extract — §1.5 Original contribution to knowledge)", body: "This thesis makes three contributions to knowledge that are, individually and collectively, original. First, the three-mechanism architectural model proposes a novel decomposition of algorithmic curation into separately measurable design properties — a decomposition that has not previously appeared in the political-communication, media-psychology, or HCI literatures. Second, Study 2's between-subjects, 12-week design provides the first causal estimate of feed-architecture effects on opinion revisability that is independent of content. Third, Study 3 develops and tests a participant-co-designed regulatory framework — a methodological contribution that bridges deliberative-democratic theory with empirical platform-policy research. Each contribution is independently defensible; together, they constitute the original contribution to knowledge claimed by this thesis." },
      { name: "Chapter 3: Theoretical Framework (extract — §3.2 Selected framework)", body: "The thesis adopts and extends the Elaboration Likelihood Model (Petty & Cacioppo, 1986) as the cognitive backbone of the theoretical framework, augmented by recent work on dual-process theory under temporal constraint (Cowan, 2017; Pennycook & Rand, 2022) and by Bail's (2021) sociology of affective polarisation. The ELM provides the cognitive route distinction (central vs. peripheral); dual-process theory provides the temporal threshold at which the central route becomes inaccessible; and Bail's framework provides the identity-binding mechanism by which affective opinions become resistant to revision. The three-mechanism architectural model proposed in §3.4 integrates these strands into a single causally explicit framework." },
      { name: "Chapter 4: Methodology (extract — §4.7 Ethical considerations)", body: "Ethical approval was secured for each study separately and collectively (UREC Refs 2024/SOC/0143, 2024/SOC/0211, 2025/SOC/0027). The experimental study introduced two non-trivial considerations: first, that randomly assigning participants to chronological feeds might temporarily disrupt their information environment; second, that political-opinion measurement is intrinsically sensitive. The first was addressed by allowing participants to revert their feeds at any time with no consequence for retention in the study, by full debriefing, and by demonstrating in pilot work that the chronological condition produced no measurable distress (PHQ-9 Δ = 0.02 over 12 weeks). The second was addressed by collecting political opinions under pseudonymisation, by aggregating data above the constituency level in reporting, and by securing explicit re-consent at three time points." },
      { name: "Chapter 7: Discussion (extract — §7.4 Why architecture, not content?)", body: "A persistent question across the three studies is why intervening at the architectural level produces larger and more durable effects than intervening at the content level (Bail et al., 2018; Pennycook & Rand, 2022). The three-mechanism model proposed in Chapter 3 supplies the answer. Content interventions act late in the cognitive chain — after temporal compression has already foreclosed central-route processing and after affective substitution has already taken place. Architectural interventions act *earlier* in the chain: they restore the cognitive conditions under which content can be processed centrally at all. This is consistent with a broader pattern in behavioural science (Thaler & Sunstein, 2008): interventions that change the choice architecture are systematically more durable than interventions that change choices within a fixed architecture. The thesis's contribution is to show that the same logic applies to political-opinion formation under algorithmic feeds." },
      { name: "Chapter 8: Conclusions (extract — §8.6 Recommendations for future research)", body: "Three lines of future research follow directly from this thesis. First, replication of Study 2 in non-UK democracies — particularly in jurisdictions with different platform-regulation regimes (EU under the DSA; the US; India) — would establish the generalisability of the architectural-effects finding. Second, the three-mechanism model should be tested in non-political domains (health information, climate communication) where opinion formation is similarly consequential. Third, the co-design methodology developed in Study 3 should be extended to other regulated industries; its success in producing a Parliament-tabled regulatory framework suggests it may have wider applicability." }
    ],
    walkthrough: [
      { step: "Original contribution", note: "§1.5 is the doctoral-specific section. Spell out exactly what is new and defend each claim independently — this is what the viva will probe." },
      { step: "Theoretical framework chapter", note: "Doctoral-level work needs an explicit Chapter 3 that sets out, justifies, and operationalises the framework — not just an embedded paragraph in the lit review." },
      { step: "Multiple studies", note: "Most doctoral theses contain 2–4 linked studies. Each gets its own findings chapter (Ch.5, Ch.6); the discussion (Ch.7) integrates across them." },
      { step: "Viva-readiness", note: "Every claim should be defensible. Limitations should be acknowledged proactively — the worst question in a viva is one you didn't anticipate." },
      { step: "Methodological contribution", note: "Doctoral work often contributes a method as well as findings (here, the co-design methodology). Make it explicit." }
    ]
  }
};

window.SAMPLE_ESSAYS = SAMPLE_ESSAYS;
